baseurl = "http://luiz.mascarenhas.it"
languageCode = "en-us"
title = "Luiz Mascarenhas"
theme = "Luiz Mascarenhas"
Paginate = 10

[params]
  twitterName = "luizfernando2"
  githubName = "lmascarenhas"
  description = "Infrastructure Analyst and DevOps Enthusiast"
  google_analytics = "UA-xxxxxx-xx"
